const filters = [
  { name: 'Normal', className: 'none' },
  { name: '1977', className: '1977' },
  { name: 'Aden', className: 'aden' },
  { name: 'Amaro', className: 'amaro' },
  { name: 'Ashby', className: 'ashby' },
  { name: 'Brannan', className: 'brannan' },
  { name: 'Brooklyn', className: 'brooklyn' },
  { name: 'Charmes', className: 'charmes' },
  { name: 'Clarendon', className: 'clarendon' },
  { name: 'Crema', className: 'crema' },
  { name: 'Dogpatch', className: 'dogpatch' },
  { name: 'Earlybird', className: 'earlybird' },
  { name: 'Gingham', className: 'gingham' },
  { name: 'Ginza', className: 'ginza' },
  { name: 'Hefe', className: 'hefe' },
  { name: 'Helena', className: 'helena' },
  { name: 'Hudson', className: 'hudson' },
  { name: 'Inkwell', className: 'inkwell' },
  { name: 'Kelvin', className: 'kelvin' },
  { name: 'Kuno', className: 'juno' },
  { name: 'Lark', className: 'lark' },
  { name: 'Lo-Fi', className: 'lofi' },
  { name: 'Ludwig', className: 'ludwig' },
  { name: 'Maven', className: 'maven' },
  { name: 'Mayfair', className: 'mayfair' },
  { name: 'Moon', className: 'moon' },
  { name: 'Nashville', className: 'nashville' },
  { name: 'Perpetua', className: 'perpetua' },
  { name: 'Poprocket', className: 'poprocket' },
  { name: 'Reyes', className: 'reyes' },
  { name: 'Rise', className: 'rise' },
  { name: 'Sierra', className: 'sierra' },
  { name: 'Skyline', className: 'skyline' },
  { name: 'Slumber', className: 'slumber' },
  { name: 'Stinson', className: 'stinson' },
  { name: 'Sutro', className: 'sutro' },
  { name: 'Toaster', className: 'toaster' },
  { name: 'Valencia', className: 'valencia' },
  { name: 'Vesper', className: 'vesper' },
  { name: 'Walden', className: 'walden' },
  { name: 'Willow', className: 'willow' },
  { name: 'X-Pro II', className: 'xpro-ii' },
];

export default filters;
