version: '3.8'

networks:
  instalura:
    name: instalura
    driver: bridge

services:
  instalura:
    image: node:lts
    container_name: instalura
    restart: unless-stopped
    volumes:
      - ../:/usr/src/service
    working_dir: /usr/src/service
    command: bash -c "npm i && npm run dev"
    ports:
      - 3000:3000
    networks:
      - instalura
